# Generated by Django 3.1.14 on 2025-02-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name_of_pokemon_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name_of_pokemon_jp',
            new_name='name_jp',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name_of_pokemon_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='photo_of_pokemon',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='name_of_pokemon_ru',
            new_name='name_ru',
        ),
    ]
