# Generated by Django 3.1.14 on 2025-02-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20250202_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='name_ru',
            new_name='pokemon',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_of_pokemons', verbose_name='Фотография'),
        ),
    ]
